### PR TITLE
Add PROPOSAL.md with gov proposal description

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/multichain-auditor/12)

### CODE REVIEW

**Review by keyleu — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/multichain-auditor/12)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`PROPOSAL.md` line 6 at r1](https://reviewable.io/reviews/CoreumFoundation/multichain-auditor/12#-Npu1fMnDIAKixDSOQve:-Npu1fMnDIAKixDSOQvf:bp2tzhq) ([raw file](https://github.com/CoreumFoundation/multichain-auditor/blob/cd328b910321a4fc1bfaf73bc87a146d6ce1679c/PROPOSAL.md#L6)):*
> ```Markdown
> 
> This proposal aims to address the compensation for users affected by the funds locked in the Multichain centralized bridge,
> which serves as the link between the XRPL (XRP Ledger) and Coreum blockchains.
> ```

nit: blockchain
___
*[`PROPOSAL.md` line 26 at r1](https://reviewable.io/reviews/CoreumFoundation/multichain-auditor/12#-Npu1tIICRtsDO-Cpys0:-Npu1tIICRtsDO-Cpys1:b-q0w0gj) ([raw file](https://github.com/CoreumFoundation/multichain-auditor/blob/cd328b910321a4fc1bfaf73bc87a146d6ce1679c/PROPOSAL.md#L26)):*
> ```Markdown
>  with **73,941.612919 COREUM**, this address will be used for the fund distribution. 
>  This has already been done in tx: [`56891F462288B4DAAC6B10C95F66D6385957D1F5656D541280B5A417D9754C9F`](https://explorer.coreum.com/coreum/transactions/56891F462288B4DAAC6B10C95F66D6385957D1F5656D541280B5A417D9754C9F)
> 2. Initiate a Community pools spend proposal to allocate **86,264.142268 COREUM** from the Community pool to the address
> ```

nit: Community pool
___
*[`PROPOSAL.md` line 36 at r1](https://reviewable.io/reviews/CoreumFoundation/multichain-auditor/12#-Npu2-iM3RwW4fKSKS5p:-Npu2-iM3RwW4fKSKS5q:b-c7hxjz) ([raw file](https://github.com/CoreumFoundation/multichain-auditor/blob/cd328b910321a4fc1bfaf73bc87a146d6ce1679c/PROPOSAL.md#L36)):*
> ```Markdown
> - the source code used to generate the reports is also included in this GitHub repository
> 
> Note that we have chosen approach with distribution address because we don't want to create 28 Community Pool spend
> ```

nit: an approach

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/multichain-auditor/12)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/multichain-auditor/12)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dzmitryhil, @keyleu, @miladz68, and @wojtek-coreum)

___
*[`PROPOSAL.md` line 26 at r1](https://reviewable.io/reviews/CoreumFoundation/multichain-auditor/12#-Npu1tIICRtsDO-Cpys0:-Npu4-EcBEpEu9UEHIQu:betezea) ([raw file](https://github.com/CoreumFoundation/multichain-auditor/blob/cd328b910321a4fc1bfaf73bc87a146d6ce1679c/PROPOSAL.md#L26)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

nit: Community pool
</blockquote></details>

resolved in another place

**Review by keyleu — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/multichain-auditor/12)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/multichain-auditor/12)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Pull request merged**
